/** Double vowel / vowel-team examples for the lesson panel */
export const doubleVowelExamples = [
  {
    letters: 'ee',
    word: 'Tree',
    words: ['see', 'meet', 'tree', 'feet', 'green'],
    icon: '🌳',
    soundLabel: 'long E',
    tip: 'Two e\'s together say "ee"!',
    parts: ['Tr', 'ee'],
  },
  {
    letters: 'oo',
    word: 'Moon',
    words: ['moon', 'book', 'pool', 'food', 'door'],
    icon: '🌙',
    soundLabel: 'long O',
    tip: 'Two o\'s together say "oo"!',
    parts: ['M', 'oo', 'n'],
  },
  {
    letters: 'ai',
    word: 'Rain',
    icon: '🌧️',
    soundLabel: 'ay',
    tip: 'A and I work as a team!',
    parts: ['R', 'ai', 'n'],
    words: ['rain', 'snail', 'rail', 'tail', 'train'],
  },
  {
    letters: 'oa',
    word: 'Boat',
    icon: '⛵',
    soundLabel: 'oh',
    tip: 'O and A float like a boat!',
    parts: ['B', 'oa', 't'],
    words: ['boat', 'coat', 'road', 'soap', 'goat'],
  },
  {
    letters: 'ay',
    word: 'Play',
    icon: '🎮',
    soundLabel: 'ay',
    tip: 'A and Y love to play!',
    parts: ['Pl', 'ay'],
    words: ['play', 'day', 'say', 'way', 'pay'],
  },
];
